data_ingestion:
  ticker: GOOGL
  start_date: '2020-01-01'
  end_date: '2025-10-21'

data_transformation:
  sma_window: 14
  ema_window: 14
  rsi_window: 14
  bb_window: 20
  bb_dev: 2
  kmeans_clusters: 3

model_trainer:
  objective: 'binary:logistic'
  eval_metric: 'logloss'
  random_state: 42
  split_ratio: 0.8

alerting:
  watchlist: ['AAPL', 'MSFT', 'NVDA', 'TSLA']
  recipient_email: "your_email@gmail.com"
