name: Scheduled Model Retraining

on:
  schedule:
    # Runs every Sunday at 00:00 UTC (5:30 AM IST)
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Make sure this matches your local Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run training pipeline
        run: python run_pipeline.py

      - name: Commit and push artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add artifacts/
          git diff-index --quiet HEAD || git commit -m "Automated retraining: Update model artifacts" && git push
